version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realworld
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  realworld:
    build: .
#    environment:
#      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/realworld
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres-data: